---
ci:
    - changed-files:
          - any-glob-to-any-file: ".github/**"
dev_container:
    - changed-files:
          - any-glob-to-any-file: ".devcontainer/**"
configuration:
    - changed-files:
          - any-glob-to-any-file: [".*", "*.js", "*.json", "*.toml", "*.yaml", "*.yml"]
documentation:
    - changed-files:
          - any-glob-to-any-file: ["**.md", "docs/**", "LICENSE"]
valentina:
    - changed-files:
          - any-glob-to-any-file: ["src/**"]
tests:
    - changed-files:
          - any-glob-to-any-file: ["tests/**"]
dependencies:
    - changed-files:
          - any-glob-to-any-file: "*.lock"
