---
github_actions:
    - changed-files:
          - any-glob-to-any-file: ".github/**"
dev_container:
    - changed-files:
          - any-glob-to-any-file: ".devcontainer/**"
configuration:
    - changed-files:
          - any-glob-to-any-file: [".*", "*.js", "*.json", "*.toml", "*.yaml", "*.yml"]
documentation:
    - changed-files:
          - any-glob-to-any-file: ["**.md", "docs/**", "LICENSE"]
python:
    - changed-files:
          - any-glob-to-any-file: ["src/**", "tests/**"]
dependencies:
    - changed-files:
          - any-glob-to-any-file: "*.lock"
