---
name: "Automated Tests"

on:
    workflow_call:
    workflow_dispatch:
    push:
        paths:
            - ".github/workflows/automated-tests.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "poetry.lock"
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths:
            - ".github/workflows/automated-tests.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "poetry.lock"

env:
    VALENTINA_LOG_FILE: "/tmp/valentina.log"
    VALENTINA_TEST_MONGO_URI: "mongodb://localhost:27017"
    VALENTINA_TEST_MONGO_DATABASE_NAME: "valentina-test"
    VALENTINA_MONGO_URI: ""
    VALENTINA_MONGO_DATABASE_NAME: ""
    VALENTINA_DISCORD_TOKEN: ""
    VALENTINA_GUILDS: ""
    VALENTINA_OWNER_CHANNELS: ""

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-python-code:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11"]
        steps:
            - name: Harden Security Runner
              uses: step-security/harden-runner@v2
              with:
                  egress-policy: block
                  disable-sudo: true
                  allowed-endpoints: >
                      api.github.com:443
                      api.snapcraft.io:443
                      files.pythonhosted.org:443
                      github.com:443
                      install.python-poetry.org:443
                      *.docker.com:443
                      pypi.org:443
                      python-poetry.org:443
                      *.docker.io:443
                      storage.googleapis.com:443

            # ----------------------------------------------
            #    Install python and checkout repository
            # ----------------------------------------------

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            #    install Mongo
            # ----------------------------------------------

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.11.0
              with:
                  mongodb-version: "7.0.2"

            # ----------------------------------------------
            #    Install poetry and project dependencies
            # ----------------------------------------------

            - name: Setup Python and Poetry
              uses: ./.github/actions/setup-poetry

            # ----------------------------------------------
            #    run linters
            # ----------------------------------------------

            - name: lint with ruff
              run: poetry run ruff --extend-ignore=I001,D301,D401 src/
            - name: check pyproject.toml
              run: poetry run poetry check

            # ----------------------------------------------
            #    run test suite
            # ----------------------------------------------
            - name: Run tests with pytest
              run: |
                  poetry run coverage run
                  poetry run coverage report
                  poetry run coverage xml
