---
name: "Automated Tests"

on:
    workflow_call:
    workflow_dispatch:
    push:
        paths:
            - ".github/workflows/automated-tests.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "poetry.lock"
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths:
            - ".github/workflows/automated-tests.yml"
            - ".github/actions/**"
            - "**.py"
            - "pyproject.toml"
            - "poetry.lock"

env:
    VALENTINA_LOG_FILE: "/tmp/valentina.log"
    VALENTINA_TEST_MONGO_URI: "mongodb://localhost:27017"
    VALENTINA_TEST_MONGO_DATABASE_NAME: "valentina-test"
    VALENTINA_MONGO_URI: ""
    VALENTINA_MONGO_DATABASE_NAME: ""
    VALENTINA_DISCORD_TOKEN: ""
    VALENTINA_GUILDS: ""
    VALENTINA_OWNER_CHANNELS: ""

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-python-code:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11", "3.12"]
        steps:
            - name: Harden Security Runner
              uses: step-security/harden-runner@v2
              with:
                  egress-policy: block
                  disable-sudo: true
                  allowed-endpoints: >
                      *.cloudflare.docker.com:443 *.codecov.io:443 *.docker.com:443 *.docker.io:443 *.github.com:443 *.googleapis.com:443 *.pythonhosted.org:443 api.snapcraft.io:443 astral.sh:443 codecov.io:443 github.com:443 *.githubusercontent.com:443 pypi.org:443


            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            #    Install and run MongoDB
            # ----------------------------------------------

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.11.0
              with:
                  mongodb-version: "8.0"

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            # Run tests
            # ----------------------------------------------

            - name: lint with ruff
              shell: bash
              run: uv run ruff check --no-fix src/

            - name: Run tests
              shell: bash
              run: uv run pytest tests/

            # ----------------------------------------------
            # Cleanup cache
            # ----------------------------------------------

            - name: Minimize uv cache
              shell: bash
              run: uv cache prune --ci
