---
name: "Create Release"

on:
    push:
        tags:
            - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: write

jobs:
    autorelease:
        name: Create Release
        runs-on: "ubuntu-latest"
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11"]
        steps:
            - name: Harden Security Runner
              uses: step-security/harden-runner@v2
              with:
                  egress-policy: block
                  disable-sudo: true
                  allowed-endpoints: >
                      *.cloudflare.docker.com:443 *.codecov.io:443 *.docker.com:443 *.docker.io:443 *.github.com:443 *.googleapis.com:443 *.pythonhosted.org:443 api.snapcraft.io:443 astral.sh:443 codecov.io:443 github.com:443 *.githubusercontent.com:443 pypi.org:443


            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            #    Grab version number
            # ----------------------------------------------

            - name: Add version to environment vars
              run: |
                  PROJECT_VERSION=$(python -c 'import tomli; print(tomli.load(open("pyproject.toml", "rb"))["project"]["version"])')
                  echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV

            # ----------------------------------------------
            # Confirm we did, in fact, update the version
            # ----------------------------------------------

            - name: Check if tag version matches project version
              run: |
                  TAG=$(git describe HEAD --tags --abbrev=0)
                  echo $TAG
                  echo $PROJECT_VERSION
                  if [[ "$TAG" != "v$PROJECT_VERSION" ]]; then exit 1; fi
                  echo "CURRENT_TAG=refs/tags/${TAG}" >> $GITHUB_ENV

            # ----------------------------------------------
            # Generate release notes
            # ----------------------------------------------

            # - name: Release Notes
            #   run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s' --no-merges >> ".github/RELEASE-TEMPLATE.md"

            - name: Get notes
              id: generate_notes
              uses: anmarkoulis/commitizen-changelog-reader@master
              with:
                  tag_name: ${{ env.CURRENT_TAG }}
                  changelog: CHANGELOG.md

            # ----------------------------------------------
            # Build draft release (Note: Will need to manually publish)
            # ----------------------------------------------

            - name: Create Release Draft
              uses: softprops/action-gh-release@v2
              with:
                  body: ${{join(fromJson(steps.generate_notes.outputs.notes).notes, '')}}
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
