---
name: "Upload to Codecov"

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Automated Tests"]
        types:
            - completed
        branches:
            - main

env:
    VALENTINA_LOG_FILE: "/tmp/valentina.log"
    VALENTINA_TEST_MONGO_URI: "mongodb://localhost:27017"
    VALENTINA_TEST_MONGO_DATABASE_NAME: "valentina-test"
    VALENTINA_MONGO_URI: ""
    VALENTINA_MONGO_DATABASE_NAME: ""
    VALENTINA_DISCORD_TOKEN: ""
    VALENTINA_GUILDS: ""
    VALENTINA_OWNER_CHANNELS: ""

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    upload-coverage:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11"]
        steps:
            - name: Harden Security Runner
              uses: step-security/harden-runner@v2
              with:
                  egress-policy: block
                  disable-sudo: true
                  allowed-endpoints: >
                      *.cloudflare.docker.com:443 *.codecov.io:443 *.docker.com:443 *.docker.io:443 *.github.com:443 *.googleapis.com:443 *.pythonhosted.org:443 api.snapcraft.io:443 astral.sh:443 codecov.io:443 github.com:443 *.githubusercontent.com:443 pypi.org:443


            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            #    Install and run MongoDB
            # ----------------------------------------------

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.11.0
              with:
                  mongodb-version: "8.0"

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            # Run tests
            # ----------------------------------------------

            - name: Run tests with pytest
              run: |
                  uv run coverage run
                  uv run coverage report
                  uv run coverage xml
            # ----------------------------------------------
            #             upload coverage stats
            # ----------------------------------------------
            - name: Upload coverage
              uses: codecov/codecov-action@v4
              with:
                  files: reports/coverage.xml
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'The triggering workflow failed'
